### ISSUE TITLE
Test and release 5.x data model epic

### ISSUE THREAD

**Issue by hslh** [molgenis/molgenis-emx2#4147]
[Decision register](https://umcgonline.sharepoint.com/:x:/r/sites/SGCohortcatalogues/_layouts/15/Doc.aspx?sourcedoc=%7B5D46FA50-6B7B-465A-A88A-2E29610B2A9B%7D&file=Decision%20register%20and%20test%20log%20for%20SSR%20bugs.xlsx&action=default&mobileredirect=true)

**What version of EMX2 are you using (see footer)**
v10.109.5-SNAPSHOT on preview server 4114

**Describe the bug**
I went through the manual tests for the flat data model on the preview server for #4114 . This is the resulting list of things to fix.

- [x] #4234
- [x] LATER ??? #4340
--- loslaten, networks laat zien gewoon wat er ingevuld is
- [x] #4342
- [x] #4347 
- [x] Eleanor design: ‘About’-page for a network has only website and description, most content is missing (e.g. partners, funding, variables, cohorts). <br> See: $testCatalogue/ssr-catalogue/testNetworkofNetworks/about-catalogue. (test 1 step 13/test 2 step 11) To be fixed in #4296   EDIT: The fields we see on the 'About' page for a network(of networks) still need to be decided upon. 'Population' doesn't strike me as something you can generalise on over a whole network, eg.
--- loslaten, network of networks laat zien gewoon wat er ingevuld is
- [ ] #4320  NOT BLOCKING BUT FOR NEXT SPRINT

- [x] #4244
- [x] On variable page, the ‘Definition’-section is called ‘Description’ in the sidebar and ‘Harmonisation Details Per Collection’ is called ‘Harmonisation Details Per Data Source’ in sidebar. <br> See: $testCatalogue/ssr-catalogue/testNetwork1/variables/testVarRepeats_-testNetwork1-cdm_1-testNetwork1?keys={"name":"testVarRepeats_","collection":{"id":"testNetwork1"},"dataset":{"name":"cdm_1","collection":{"id":"testNetwork1”}}}. (test 4 step 10)
- [x] #4246
- [x] On cohort page, in the ‘General Design’-section, the ‘Cohort Design’, in this case ‘longitudinal’, isn’t displayed. <br> See: $testCatalogue/ssr-catalogue/all/cohorts/testCohort2. (test 5 step 18)
- [x] #4247
- [x] #4343
- [x] #4256

ISSUES FOUND IN VERSION v11.11.1-SNAPSHOT
- [x] #4254
- [x] #4341
- [x] The harmonisation matrix and the info per cohort don't match, for some reason. testvarrepeats in preview ([here](https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables/testVarRepeats_-testNetwork1-cdm_1-testNetwork1?keys={%22name%22:%22testVarRepeats_%22,%22resource%22:{%22id%22:%22testNetwork1%22},%22dataset%22:{%22name%22:%22cdm_1%22,%22resource%22:{%22id%22:%22testNetwork1%22}}}#harmonisation-details-per-source)) gives different results in the matrix to what you see below when you click on testcohort3 in the harmonisation details per data source.  Test plan 4 step 12, test plan 6 step 6. See comment below.
--> test data fixen en dan controleren
- [x] The contact page (behind button 'Contact' on the cohort detail page) doesn't seem to have the updates we made in the big release in July, i.e. pop-up with "Name of test cohort 2", Contact, Name entry field, Email entry field, Organisation entry field, Topic dropdown, Message entry field, "or contact us at: [molgenis-support@umcg.nl](mailto:molgenis-support@umcg.nl)", Send button" Test plan 5, step 6
--> testen in acc (emailsettings nodig)
EDIT: 16-10-24 this doesn't work in acc. Assume the email settings are still the same as before?
We also need to change the email address in the test data to support@molgenis.org.

- [x] The start/end year of cohort [testcohort2](https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/testCohort2) should be '1955-ongoing', not 'not available'  Test plan 5, step 24, and test plan 9 step 10 (different years for cohort 1 but the same issue)
--> bewust veranderd ivm DCAT
- [x] The headings on the left hand side of the cohort page are missing 'Variables & Topics' in between Contributors and Available Data & Samples. eg on https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/testCohort2   Test plan 5, step 11 --> Blok Variables & Topics wordt eerst weggehaald en daarna goed gedefinieerd en gespecificeerd.
- [x] The text under 'Variables & Topics' is still a placeholder text and needs to be updated or removed. Test plan 5 (no test step for this new block yet)
--> Blok Variables & Topics wordt eerst weggehaald en daarna goed gedefinieerd en gespecificeerd.
- [x] #4287
- [x] #4300 
- [x] Data access fee and prelinked fields not shown under Access conditions  Test plan 5 step 57  (compare test plan 9 step 28, where they ARE shown because they are 'true'). --> TBD, see https://github.com/molgenis/GCC/issues/475
- [x] #4303 

ISSUES FOUND IN ACC WITH V11.20.0
- [x] network logos not shown on resource detail page: https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/EHEN/cohorts/ABCD
- [x] logo's networks not show on network homepage

ISSUES FOUND IN ACC WITH V11.16.2

- [x] #4322

ISSUES FOUND IN ACC WITH V11.20.6

- [x] #4366
- [ ] On the variable detail page, the headings are 'harmonisation status per data source' and 'harmonisation details per data source'. Use of the words 'data source' strikes me as a little confusing (data sources are just one of the resource types which can have harmonised variables). Suggestion: change this to "harmonisation status per source of data" and "harmonisation details per source of data". Small difference but subtly quite important! eg https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/variables/testVarRepeats_-testNetwork1-cdm_1-testNetwork1?keys={%22name%22:%22testVarRepeats_%22,%22resource%22:{%22id%22:%22testNetwork1%22},%22dataset%22:{%22name%22:%22cdm_1%22,%22resource%22:{%22id%22:%22testNetwork1%22}}} . See also #4386 
NOT BLOCKING BUT FOR NEXT SPRINT

- [x] #4367  NOT blocking - and also closed without change, the collection event dates can stay as they are

- [x] #4368  NOT blocking

- [ ] We have dropped the 'variables and topics' tile in the cohort (no bad thing) but we must implement a link to the cohort's source variables very soon. We've discussed and decided before, see spec here: https://umcgonline.sharepoint.com/:w:/r/sites/SGCohortcatalogues/Gedeelde%20documenten/Test%20Activities/Specs%20for%20feature%20requests/20240924%20Variables%20%26%20Topics.docx?d=w53fdf3aa9eb14212a2f8ef948c8197e9&csf=1&web=1&e=WU6Tce
NOT BLOCKING BUT FOR NEXT SPRINT see stories GCC no. 144 and 711

ISSUES FOUND IN V11.25.0
- [ ] #4413 NOT blocking
- [ ] #4415 NOT BLOCKING BUT FOR NEXT SPRINT

ISSUES FOUND IN V11.25.1
- [x] #4422 not cosmetically blocking but we do need to check that adding the layer 'collections' hasn't upset other functionality (as it seems to have done here)

ACTIONS FOR HESSEL, JORIS, ELEANOR AND OTHERS SEPARATE FROM SOFTWARE CHANGES AND NOT LISTED ABOVE
- [x] get clarity about how (eg) the cohort page does or does not look the same as the network page --> which differences between resources do we need to test?
--- we houden het bij cohorten pagina test met cohort dat zoveel mogelijk ingevuld is
- [x] sort out the email settings in acc so that we can test the Contact page on a cohort
--- doet Hessel <- note that this is a schema-level setting, so we'll have to repeat this every time we load a schema with a fresh set of demo data
- [x] include design schematic in test data
--- wait for merging and deployment of #4411 
- [x] decide on final design of All Resources page
--- need a few suggestions for Morris to choose from 
--- 3 CTAs on the All Resources page: 1) Resources 2) Networks 3) Variables
--- text under Resoures moet het uitleggen
--- clicking on Resources --> pagina van bv cohort studies maar dan met extra filter om resource type te kiezen
--- PR aanmaken
--- Eleanor maakt opzet: [here](https://umcgonline.sharepoint.com/:p:/r/sites/SGCohortcatalogues/Gedeelde%20documenten/Test%20Activities/Specs%20for%20feature%20requests/20241023%20Search%20All%20page.pptx?d=w3e98f5576cc241eeac7ca5a61ba34c02&csf=1&web=1&e=wAGHbZ)
- [x] finish test plan (and test data) for All Resources page
- [x] check test data for variable asthma_0 and Pelagie, whether it's correct (Test plan 7)
- [x] finalise variable numbers displayed etc in test plans (reinstate old variables or not, is it worth it or do we test everything sufficiently as it is?)
--- Eleanor checkt of de extra variabel nodig is DONE: the variable testVarLang2 which had been removed is not crucial: we have another variable with no mappings (testVarCategorical_) which tests when variables without mappings are/aren't shown.
--- update the test plans using variables to remove mentions of testVarLang2, change mentions of testVarLang1 into mentions of testVarLang and revise the numbers of variables shown at various stages 
- [x] check data model of the test data in testCatalogue (warning messages about columns when uploading)
- [x] test data for test plan 9: fill in multiple values where this hasn't happened yet
- [x] Update testCatalogue schemata on dev and acc to reflect changes in test data
- [x] Edit all the test plans to include the new navigation ("Collection CTA")
- [x] go through all the test plans again once we think everything crucial has been fixed
- [x] communicate with users about timing of the release (issue 747 in GCC repo)
- [x] check that there are no blocking issues for UMCG before we go live

ISSUES in v25.0:
- [ ] #4419 not blocking: ugly white space in variable details page
- [x] #4264 networks staging cannot display resources table
- [ ] #4428: harmonisation details (syntax and such) for Year 0 are not shown NOT BLOCKING BUT FOR NEXT SPRINT
- [ ] #4429: order and names of attributes do not always match the data model NOT BLOCKING BUT FOR NEXT SPRINT

**Comment by EleanorHyde-UMCG** [comment]
This item has been **partially** solved:

- [ ] On cohort page, the ‘Partners’-section is missing. The ‘Available Data & Samples’-section is there, but it is missing from the sidebar. ’Networks’-section is called ‘Networks’ in sidebar, but ‘Part of Networks’ in the main content screen.

See: $testCatalogue/ssr-catalogue/testNetwork1/cohorts/testCohort2. (test 3 step 6b/test 5 step 11, 53/test 9 step 26)

Before the big release in July, we absorbed Partners into Contributors (but unfortunately omitted to adjust this test plan 3). However, Organisations should also have been absorbed into Contributors.  What we currently have in prod is:

Description
General Design
Population
Contributors
Available Data & Samples
Subpopulations
Collection Events
Datasets
Networks
Publications
Access Conditions
Funding & Acknowledgements
Documentation

So what still needs to be fixed for this item is:
- [ ] remove Organisations as a separate heading on the cohort detail page and absorb it into Contributors (as it is in prod)
- [ ] make the heading/menu item for Networks / Part of Networks consistent ('part of networks' is new and may have been decided upon within the flat data model group?)

**Comment by EleanorHyde-UMCG** [comment]
Pop-up for 'about statuses' in the harmonisation matrix (eg on a variable detail page such as [this](https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables/testVarRepeats_-testNetwork1-cdm_1-testNetwork1?keys={%22name%22:%22testVarRepeats_%22,%22resource%22:{%22id%22:%22testNetwork1%22},%22dataset%22:{%22name%22:%22cdm_1%22,%22resource%22:{%22id%22:%22testNetwork1%22}}}) in preview) needs to be brought in line with the new labels for what used to be labelled 'cohorts'.   The current text is this:

Pop up should show 'completed: cohort was able to fully map to the harmonised variables'; 'partially: cohort was able to partially map to the harmonised variable'; 'No data: no harmonisation data is available'.

Test plan 4 step 11

I've added a new item in the list above.

**Comment by EleanorHyde-UMCG** [comment]
The harmonisation matrix and the info per cohort don't match, for some reason. testvarrepeats in preview ([here](https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables/testVarRepeats_-testNetwork1-cdm_1-testNetwork1?keys={%22name%22:%22testVarRepeats_%22,%22resource%22:{%22id%22:%22testNetwork1%22},%22dataset%22:{%22name%22:%22cdm_1%22,%22resource%22:{%22id%22:%22testNetwork1%22}}}#harmonisation-details-per-source)) gives different results in the matrix to what you see below when you click on testcohort3 in the harmonisation details per data source.  Test plan 4 step 12.

Have added this to the list above.

**Comment by EleanorHyde-UMCG** [comment]
Data banks are included in the harmonisation matrix for a network. Do we expect data banks to have harmonised variables? (test plan 4 step 15.

**Comment by EleanorHyde-UMCG** [comment]
The number of variables for a network is incorrect (I suspect a change made for the network-of-networks works has something to do with this). The test plan has been changed since the big release in July, also for the network of networks, to include another variable ga_lmp (under testcohort2) but this is not picked up in preview.

[Overview page of network](https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1) --> number of variables should be 8, not 7. Clicking on the variables should also give 8 variables, including ga_lmp, which has been mapped by testcohort2 (which belongs to testnetwork1). 

Let's discuss and check what should be happening here (I wasn't involved in the change of test data). @BrendaHijmans ?

**Comment by EleanorHyde-UMCG** [comment]
The contact page (behind button 'Contact') doesn't seem to have the updates we made in the big release in July, i.e. pop-up with "Name of test cohort 2", Contact, Name entry field, Email entry field, Organisation entry field, Topic dropdown, Message entry field, "or contact us at: [molgenis-support@umcg.nl](mailto:molgenis-support@umcg.nl)", Send button"

Test plan 5, step 6

**Comment by EleanorHyde-UMCG** [comment]
The start/end year of cohort [testcohort2](https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/testCohort2) should be '1955-ongoing', not 'not available'  Test plan 5, step 24

**Comment by EleanorHyde-UMCG** [comment]
The headings on the left hand side of the cohort page are missing 'Variables & Topics' in between Contributors and Available Data & Samples. eg on https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/testCohort2
Test plan 5, step 11

Have added to the list above.

**Comment by EleanorHyde-UMCG** [comment]
The text under 'Variables & Topics' is still a placeholder text and needs to be updated or removed. Test plan 5 (no test step for this new block yet)

Have added to the list above.

**Comment by EleanorHyde-UMCG** [comment]
What do we expect to happen when pressing the 'Harmonised varialbes' button on the cohort page?  eg [testcohort2](https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/testCohort2)

**Comment by EleanorHyde-UMCG** [comment]
The comorbidity items in the pop-up for a subcohort are presented in random order but should be in alphabetical/numerical order.  Test plan 5 step 45

Have added to the list above.

**Comment by EleanorHyde-UMCG** [comment]
Data access fee not shown under Access conditions (bug https://github.com/orgs/molgenis/projects/15/views/1?filterQuery=data+access+fee&pane=issue&itemId=68839761)  Test plan 5 step 57

Have added to list

**Comment by EleanorHyde-UMCG** [comment]
When browsing 'all resources', there's no difference in the text under 'Cohort studies' and 'Studies' (both have "cohorts & biobanks" as explanatory text). Is this deliberate?

@BrendaHijmans

**Comment by EleanorHyde-UMCG** [comment]
> The harmonisation matrix and the info per cohort don't match, for some reason. testvarrepeats in preview ([here](https://preview-emx2-pr-4178.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/variables/testVarRepeats_-testNetwork1-cdm_1-testNetwork1?keys=%7B%22name%22:%22testVarRepeats_%22,%22resource%22:%7B%22id%22:%22testNetwork1%22%7D,%22dataset%22:%7B%22name%22:%22cdm_1%22,%22resource%22:%7B%22id%22:%22testNetwork1%22%7D%7D%7D#harmonisation-details-per-source)) gives different results in the matrix to what you see below when you click on testcohort3 in the harmonisation details per data source. Test plan 4 step 12, test plan 6 step 6.
> 
> Have added this to the list above.

Fixed by fixing the test data. The migration script meant for production data worked differently to what was intended on the (randomly filled-in) test repeated variable, meaning the number of repeats was smaller than meant to be, which in turn meant that fewer repeats were shown in the harmonisation matrix. No software fix required.

**Comment by EleanorHyde-UMCG** [comment]
All open items are now under this milestone: https://github.com/molgenis/molgenis-emx2/milestone/40
